### PR TITLE
Added CORS headers to prevent errors when using the magento API

### PR DESCRIPTION
**Pull request by BobWez98**

### CODE REVIEW

**Comment by royduin** [comment]
Awesome! Since https://github.com/michielgerritsen/magento2-extension-integration-test/pull/25 our tests are broken. The old cors patch can be removed as it's not using the php webserver anymore, see the `cors.patch` file and the `Dockerfile`

**Comment by BobWez98** [comment]
Seems like the `add_header` function isn't working properly. Closed it for now.

**Comment by michielgerritsen** [comment]
@BobWez98 Thanks for the PR! Could you share what is not working properly? So we can have a look?

**Comment by BobWez98** [comment]
We are using the Docker image in this repo for the tests in [Rapidez](https://rapidez.io/) . After nginx was added this gave API/Graphql requests CORS errors.

**Pull request closed without merging**
