### PR TITLE
🔓 Disable Magento 2FA

### PR DESCRIPTION
**Pull request by royduin**
Because you can't login to the admin panel without setting up 2FA and it's really annoying while testing.

### CODE REVIEW

**Comment by royduin** [comment]
Please merge, everybody hates 2fa in Magento 😜😇

**Comment by michielgerritsen** [comment]
If you fix:
- The merge conflict
- The failing build

i will fix it.

**Comment by royduin** [comment]
Whoehoe 🎉 fixed 🥳

**Comment by VincentBean** [comment]
Would be nice if this gets merged :)

**Pull request merged**
